CREATE TABLE claims_data (
    claim_id TEXT PRIMARY KEY,
    do_number TEXT,
    carrier TEXT,
    carrier_reference_id TEXT,
    carrier_reference_type TEXT,
    carrier_vendor_code TEXT,
    carrier_scac_code TEXT,
    claim_type TEXT,
    loss_track TEXT,
    loss_tack_code INT,
    origin_wh TEXT,
    destination_wh TEXT,
    claim_date DATE,
    filed_date DATE,
    claim_amount DECIMAL,
    approved_amount DECIMAL,
    claim_status TEXT,
    recovery_rate DECIMAL,
    days_open INT,
    owner_team TEXT,
    last_follow_up DATE,
    follow_up_status TEXT,
    time_bar_flag TEXT,
    claim_age_bucket TEXT,
    at_risk_amount DECIMAL
);